---
title: "Assignment 2: Feature Engineering, Statistical Analysis and Machine Learning"
author: "Ryan McKee (40294886)"
output:
  pdf_document:
     includes: 
         in_header: "preamble.tex"
  html_notebook: default
  html_document:
    df_print: paged
---

## Introduction

The overall objective of this project is to create A.I that will be able to recognize letters in the set {a,b,c,d,e,f,g,h,i,j}, as well as recognize smiley faces, sad faces and exclamation
marks. In this part of the assignment(assignment 2) My goals are to create a data set of hand drawn letters, smiley faces, sad faces and exclamation marks. Then perform feature engineering on
these images to calculate features such as how many black pixels exist in the image and aspect ratio. Then perform statistical analysis of the data sets using methods of statistical inference such
as using histograms and finally for this assignment implement and evaluate some machine learning models that perform classification on the data set.

# Section 1

I created my data set images for letters in set {a,...,j}, smiley faces, sad faces and exclamation marks using GIMP with images of 18x18 pixels and exporting these images as PGM files type ASCII. This 
file type stored the values of pixels on 324 separate lines each line having a value of 255 representing a white pixel or 0 representing a black pixel. In order to convert these PGM files to a matrix
representation of the image in a csv file so that these images could be more easily analysed later in the project I created an R script as shown below. This R script stores each of the files in the PGM 
image folder as a list. I then looped through this list reading the pixel values of each of the element and changing the elements value in the matrix to 0 if the element value is greater or equal to 128
or if less than I changed the value of that element in the matrix to be equal to 1. I then used write.table to write the updated matrix's to new csv file's in a folder that contains the updated data set,
and using the gsub function in the paste function for getting the file path I changed the file extensions for the file names to go from .pgm to .csv.

```{r, eval = FALSE}
{library(readr)
 library(utile.tables)
  

  # * To change the folder that contains the .pgm files
  # Just change the path in list.files() belowe to be equal
  # to the file path of the folder, and change the working_folder
  # to be equal to the file path + / *
  data_files <- list.files(path = "ai_dataset")
  working_folder <- "ai_dataset/"
  
  for(index in 1:length(data_files)){
    
    current_file <- data_files[index]
    
    current_file_path <- paste(working_folder, current_file, sep = "")
    
    pgmFile <- read_lines(file = current_file_path, skip = 4)
    imageMatrix <- matrix(pgmFile, nrow = 18, ncol = 18)
    
    for(row in 1:nrow(imageMatrix)) 
    {
      for(col in 1:ncol(imageMatrix)) 
      {
        if(imageMatrix[row,col] < 128)
        {
          imageMatrix[row,col] = 1
        }
        else
        {
          imageMatrix[row,col] = 0
        }
      }
    }
    
    imageMatrix <- t(imageMatrix)
    
    # * To change the folder that the updated dataset gets created in just change the first argument in the paste function to the file path for updated folder + / *
    write.table(imageMatrix, file = paste("csv_ai_dataset/", gsub('.pgm', '.csv', data_files[index]), sep = ""), col.names = F, row.names = F, sep = ",", quote = FALSE)
    
  }
  
  print("csv dataset has been successfully created.")
}
```


# Section 2

Your work for this section 


# Section 3

## Section 3.1

Your work for this subsection here.

## Section 3.2

Your work for this subsection here.

## Section 3.3

Your work for this subsection here.

## Section 3.4

Your work for this subsection here.

# Section 4

## Section 4.1

Your work for this subsection here.

## Section 4.2

Your work for this subsection here.

## Section 4.3

Your work for this subsection here.

## Section 4.4

Your work for this subsection here.